services:
  - type: web
    name: haitibiznis-api
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://haitibiznis-api.onrender.com
      - key: SOLUTIONIP_URL
        value: https://plopplop.solutionip.app
      - key: SOLUTIONIP_CLIENT_ID
        value: pp_1ohu5zz2tcx
